/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as BacAGraisseRouteImport } from './routes/bac-a-graisse'
import { Route as CanalisationsRouteImport } from './routes/canalisations'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as CurageCanalisationRouteImport } from './routes/curage-canalisation'
import { Route as FaqRouteImport } from './routes/faq'
import { Route as HydrocurageRouteImport } from './routes/hydrocurage'
import { Route as InspectionCameraRouteImport } from './routes/inspection-camera'
import { Route as InterventionRouteImport } from './routes/intervention'
import { Route as PompageAssainissementRouteImport } from './routes/pompage-assainissement'
import { Route as SanitaireRouteImport } from './routes/sanitaire'
import { Route as ServicesRouteImport } from './routes/services'
import { Route as SystemeRelevageRouteImport } from './routes/systeme-relevage'
import { Route as TarifsRouteImport } from './routes/tarifs'
import { Route as DebouchageCanalisationIndexRouteImport } from './routes/debouchage-canalisation.index'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const BacAGraisseRoute = BacAGraisseRouteImport.update({
  id: '/bac-a-graisse',
  path: '/bac-a-graisse',
  getParentRoute: () => rootRouteImport,
} as any)
const CanalisationsRoute = CanalisationsRouteImport.update({
  id: '/canalisations',
  path: '/canalisations',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const CurageCanalisationRoute = CurageCanalisationRouteImport.update({
  id: '/curage-canalisation',
  path: '/curage-canalisation',
  getParentRoute: () => rootRouteImport,
} as any)
const FaqRoute = FaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => rootRouteImport,
} as any)
const HydrocurageRoute = HydrocurageRouteImport.update({
  id: '/hydrocurage',
  path: '/hydrocurage',
  getParentRoute: () => rootRouteImport,
} as any)
const InspectionCameraRoute = InspectionCameraRouteImport.update({
  id: '/inspection-camera',
  path: '/inspection-camera',
  getParentRoute: () => rootRouteImport,
} as any)
const InterventionRoute = InterventionRouteImport.update({
  id: '/intervention',
  path: '/intervention',
  getParentRoute: () => rootRouteImport,
} as any)
const PompageAssainissementRoute = PompageAssainissementRouteImport.update({
  id: '/pompage-assainissement',
  path: '/pompage-assainissement',
  getParentRoute: () => rootRouteImport,
} as any)
const SanitaireRoute = SanitaireRouteImport.update({
  id: '/sanitaire',
  path: '/sanitaire',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesRoute = ServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => rootRouteImport,
} as any)
const SystemeRelevageRoute = SystemeRelevageRouteImport.update({
  id: '/systeme-relevage',
  path: '/systeme-relevage',
  getParentRoute: () => rootRouteImport,
} as any)
const TarifsRoute = TarifsRouteImport.update({
  id: '/tarifs',
  path: '/tarifs',
  getParentRoute: () => rootRouteImport,
} as any)
const DebouchageCanalisationIndexRoute =
  DebouchageCanalisationIndexRouteImport.update({
    id: '/debouchage-canalisation/',
    path: '/debouchage-canalisation/',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/bac-a-graisse': typeof BacAGraisseRoute
  '/canalisations': typeof CanalisationsRoute
  '/contact': typeof ContactRoute
  '/curage-canalisation': typeof CurageCanalisationRoute
  '/faq': typeof FaqRoute
  '/hydrocurage': typeof HydrocurageRoute
  '/inspection-camera': typeof InspectionCameraRoute
  '/intervention': typeof InterventionRoute
  '/pompage-assainissement': typeof PompageAssainissementRoute
  '/sanitaire': typeof SanitaireRoute
  '/services': typeof ServicesRoute
  '/systeme-relevage': typeof SystemeRelevageRoute
  '/tarifs': typeof TarifsRoute
  '/debouchage-canalisation/': typeof DebouchageCanalisationIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/bac-a-graisse': typeof BacAGraisseRoute
  '/canalisations': typeof CanalisationsRoute
  '/contact': typeof ContactRoute
  '/curage-canalisation': typeof CurageCanalisationRoute
  '/faq': typeof FaqRoute
  '/hydrocurage': typeof HydrocurageRoute
  '/inspection-camera': typeof InspectionCameraRoute
  '/intervention': typeof InterventionRoute
  '/pompage-assainissement': typeof PompageAssainissementRoute
  '/sanitaire': typeof SanitaireRoute
  '/services': typeof ServicesRoute
  '/systeme-relevage': typeof SystemeRelevageRoute
  '/tarifs': typeof TarifsRoute
  '/debouchage-canalisation': typeof DebouchageCanalisationIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/bac-a-graisse': typeof BacAGraisseRoute
  '/canalisations': typeof CanalisationsRoute
  '/contact': typeof ContactRoute
  '/curage-canalisation': typeof CurageCanalisationRoute
  '/faq': typeof FaqRoute
  '/hydrocurage': typeof HydrocurageRoute
  '/inspection-camera': typeof InspectionCameraRoute
  '/intervention': typeof InterventionRoute
  '/pompage-assainissement': typeof PompageAssainissementRoute
  '/sanitaire': typeof SanitaireRoute
  '/services': typeof ServicesRoute
  '/systeme-relevage': typeof SystemeRelevageRoute
  '/tarifs': typeof TarifsRoute
  '/debouchage-canalisation/': typeof DebouchageCanalisationIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/bac-a-graisse'
    | '/canalisations'
    | '/contact'
    | '/curage-canalisation'
    | '/faq'
    | '/hydrocurage'
    | '/inspection-camera'
    | '/intervention'
    | '/pompage-assainissement'
    | '/sanitaire'
    | '/services'
    | '/systeme-relevage'
    | '/tarifs'
    | '/debouchage-canalisation/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/bac-a-graisse'
    | '/canalisations'
    | '/contact'
    | '/curage-canalisation'
    | '/faq'
    | '/hydrocurage'
    | '/inspection-camera'
    | '/intervention'
    | '/pompage-assainissement'
    | '/sanitaire'
    | '/services'
    | '/systeme-relevage'
    | '/tarifs'
    | '/debouchage-canalisation'
  id:
    | '__root__'
    | '/'
    | '/bac-a-graisse'
    | '/canalisations'
    | '/contact'
    | '/curage-canalisation'
    | '/faq'
    | '/hydrocurage'
    | '/inspection-camera'
    | '/intervention'
    | '/pompage-assainissement'
    | '/sanitaire'
    | '/services'
    | '/systeme-relevage'
    | '/tarifs'
    | '/debouchage-canalisation/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BacAGraisseRoute: typeof BacAGraisseRoute
  CanalisationsRoute: typeof CanalisationsRoute
  ContactRoute: typeof ContactRoute
  CurageCanalisationRoute: typeof CurageCanalisationRoute
  FaqRoute: typeof FaqRoute
  HydrocurageRoute: typeof HydrocurageRoute
  InspectionCameraRoute: typeof InspectionCameraRoute
  InterventionRoute: typeof InterventionRoute
  PompageAssainissementRoute: typeof PompageAssainissementRoute
  SanitaireRoute: typeof SanitaireRoute
  ServicesRoute: typeof ServicesRoute
  SystemeRelevageRoute: typeof SystemeRelevageRoute
  TarifsRoute: typeof TarifsRoute
  DebouchageCanalisationIndexRoute: typeof DebouchageCanalisationIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bac-a-graisse': {
      id: '/bac-a-graisse'
      path: '/bac-a-graisse'
      fullPath: '/bac-a-graisse'
      preLoaderRoute: typeof BacAGraisseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/canalisations': {
      id: '/canalisations'
      path: '/canalisations'
      fullPath: '/canalisations'
      preLoaderRoute: typeof CanalisationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/curage-canalisation': {
      id: '/curage-canalisation'
      path: '/curage-canalisation'
      fullPath: '/curage-canalisation'
      preLoaderRoute: typeof CurageCanalisationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faq': {
      id: '/faq'
      path: '/faq'
      fullPath: '/faq'
      preLoaderRoute: typeof FaqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hydrocurage': {
      id: '/hydrocurage'
      path: '/hydrocurage'
      fullPath: '/hydrocurage'
      preLoaderRoute: typeof HydrocurageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inspection-camera': {
      id: '/inspection-camera'
      path: '/inspection-camera'
      fullPath: '/inspection-camera'
      preLoaderRoute: typeof InspectionCameraRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/intervention': {
      id: '/intervention'
      path: '/intervention'
      fullPath: '/intervention'
      preLoaderRoute: typeof InterventionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pompage-assainissement': {
      id: '/pompage-assainissement'
      path: '/pompage-assainissement'
      fullPath: '/pompage-assainissement'
      preLoaderRoute: typeof PompageAssainissementRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sanitaire': {
      id: '/sanitaire'
      path: '/sanitaire'
      fullPath: '/sanitaire'
      preLoaderRoute: typeof SanitaireRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services': {
      id: '/services'
      path: '/services'
      fullPath: '/services'
      preLoaderRoute: typeof ServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/systeme-relevage': {
      id: '/systeme-relevage'
      path: '/systeme-relevage'
      fullPath: '/systeme-relevage'
      preLoaderRoute: typeof SystemeRelevageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tarifs': {
      id: '/tarifs'
      path: '/tarifs'
      fullPath: '/tarifs'
      preLoaderRoute: typeof TarifsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/debouchage-canalisation/': {
      id: '/debouchage-canalisation/'
      path: '/debouchage-canalisation'
      fullPath: '/debouchage-canalisation/'
      preLoaderRoute: typeof DebouchageCanalisationIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BacAGraisseRoute: BacAGraisseRoute,
  CanalisationsRoute: CanalisationsRoute,
  ContactRoute: ContactRoute,
  CurageCanalisationRoute: CurageCanalisationRoute,
  FaqRoute: FaqRoute,
  HydrocurageRoute: HydrocurageRoute,
  InspectionCameraRoute: InspectionCameraRoute,
  InterventionRoute: InterventionRoute,
  PompageAssainissementRoute: PompageAssainissementRoute,
  SanitaireRoute: SanitaireRoute,
  ServicesRoute: ServicesRoute,
  SystemeRelevageRoute: SystemeRelevageRoute,
  TarifsRoute: TarifsRoute,
  DebouchageCanalisationIndexRoute: DebouchageCanalisationIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
