/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AProposRouteImport } from './routes/a-propos'
import { Route as AssuranceDecennaleRouteImport } from './routes/assurance-decennale'
import { Route as BacAGraisseRouteImport } from './routes/bac-a-graisse'
import { Route as BlogRouteImport } from './routes/blog'
import { Route as CanalisationsRouteImport } from './routes/canalisations'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as CurageCanalisationRouteImport } from './routes/curage-canalisation'
import { Route as FaqRouteImport } from './routes/faq'
import { Route as HydrocurageRouteImport } from './routes/hydrocurage'
import { Route as InspectionCameraRouteImport } from './routes/inspection-camera'
import { Route as InterventionRouteImport } from './routes/intervention'
import { Route as MentionsLegalesRouteImport } from './routes/mentions-legales'
import { Route as PolitiqueConfidentialiteRouteImport } from './routes/politique-confidentialite'
import { Route as PompageAssainissementRouteImport } from './routes/pompage-assainissement'
import { Route as RealisationsRouteImport } from './routes/realisations'
import { Route as SanitaireRouteImport } from './routes/sanitaire'
import { Route as ServicesRouteImport } from './routes/services'
import { Route as SystemeRelevageRouteImport } from './routes/systeme-relevage'
import { Route as TarifsRouteImport } from './routes/tarifs'
import { Route as UrgenceRouteImport } from './routes/urgence'
import { Route as ZonesRouteImport } from './routes/zones'
import { Route as DebouchageCanalisationIndexRouteImport } from './routes/debouchage-canalisation.index'
import { Route as DebouchageCanalisationHautsDeSeineRouteImport } from './routes/debouchage-canalisation.hauts-de-seine'
import { Route as DebouchageCanalisationParisRouteImport } from './routes/debouchage-canalisation.paris'
import { Route as DebouchageCanalisationSeineSaintDenisRouteImport } from './routes/debouchage-canalisation.seine-saint-denis'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AProposRoute = AProposRouteImport.update({
  id: '/a-propos',
  path: '/a-propos',
  getParentRoute: () => rootRouteImport,
} as any)
const AssuranceDecennaleRoute = AssuranceDecennaleRouteImport.update({
  id: '/assurance-decennale',
  path: '/assurance-decennale',
  getParentRoute: () => rootRouteImport,
} as any)
const BacAGraisseRoute = BacAGraisseRouteImport.update({
  id: '/bac-a-graisse',
  path: '/bac-a-graisse',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogRoute = BlogRouteImport.update({
  id: '/blog',
  path: '/blog',
  getParentRoute: () => rootRouteImport,
} as any)
const CanalisationsRoute = CanalisationsRouteImport.update({
  id: '/canalisations',
  path: '/canalisations',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const CurageCanalisationRoute = CurageCanalisationRouteImport.update({
  id: '/curage-canalisation',
  path: '/curage-canalisation',
  getParentRoute: () => rootRouteImport,
} as any)
const FaqRoute = FaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => rootRouteImport,
} as any)
const HydrocurageRoute = HydrocurageRouteImport.update({
  id: '/hydrocurage',
  path: '/hydrocurage',
  getParentRoute: () => rootRouteImport,
} as any)
const InspectionCameraRoute = InspectionCameraRouteImport.update({
  id: '/inspection-camera',
  path: '/inspection-camera',
  getParentRoute: () => rootRouteImport,
} as any)
const InterventionRoute = InterventionRouteImport.update({
  id: '/intervention',
  path: '/intervention',
  getParentRoute: () => rootRouteImport,
} as any)
const MentionsLegalesRoute = MentionsLegalesRouteImport.update({
  id: '/mentions-legales',
  path: '/mentions-legales',
  getParentRoute: () => rootRouteImport,
} as any)
const PolitiqueConfidentialiteRoute =
  PolitiqueConfidentialiteRouteImport.update({
    id: '/politique-confidentialite',
    path: '/politique-confidentialite',
    getParentRoute: () => rootRouteImport,
  } as any)
const PompageAssainissementRoute = PompageAssainissementRouteImport.update({
  id: '/pompage-assainissement',
  path: '/pompage-assainissement',
  getParentRoute: () => rootRouteImport,
} as any)
const RealisationsRoute = RealisationsRouteImport.update({
  id: '/realisations',
  path: '/realisations',
  getParentRoute: () => rootRouteImport,
} as any)
const SanitaireRoute = SanitaireRouteImport.update({
  id: '/sanitaire',
  path: '/sanitaire',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesRoute = ServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => rootRouteImport,
} as any)
const SystemeRelevageRoute = SystemeRelevageRouteImport.update({
  id: '/systeme-relevage',
  path: '/systeme-relevage',
  getParentRoute: () => rootRouteImport,
} as any)
const TarifsRoute = TarifsRouteImport.update({
  id: '/tarifs',
  path: '/tarifs',
  getParentRoute: () => rootRouteImport,
} as any)
const UrgenceRoute = UrgenceRouteImport.update({
  id: '/urgence',
  path: '/urgence',
  getParentRoute: () => rootRouteImport,
} as any)
const ZonesRoute = ZonesRouteImport.update({
  id: '/zones',
  path: '/zones',
  getParentRoute: () => rootRouteImport,
} as any)
const DebouchageCanalisationIndexRoute =
  DebouchageCanalisationIndexRouteImport.update({
    id: '/debouchage-canalisation/',
    path: '/debouchage-canalisation/',
    getParentRoute: () => rootRouteImport,
  } as any)
const DebouchageCanalisationHautsDeSeineRoute =
  DebouchageCanalisationHautsDeSeineRouteImport.update({
    id: '/debouchage-canalisation/hauts-de-seine',
    path: '/debouchage-canalisation/hauts-de-seine',
    getParentRoute: () => rootRouteImport,
  } as any)
const DebouchageCanalisationParisRoute =
  DebouchageCanalisationParisRouteImport.update({
    id: '/debouchage-canalisation/paris',
    path: '/debouchage-canalisation/paris',
    getParentRoute: () => rootRouteImport,
  } as any)
const DebouchageCanalisationSeineSaintDenisRoute =
  DebouchageCanalisationSeineSaintDenisRouteImport.update({
    id: '/debouchage-canalisation/seine-saint-denis',
    path: '/debouchage-canalisation/seine-saint-denis',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/a-propos': typeof AProposRoute
  '/assurance-decennale': typeof AssuranceDecennaleRoute
  '/bac-a-graisse': typeof BacAGraisseRoute
  '/blog': typeof BlogRoute
  '/canalisations': typeof CanalisationsRoute
  '/contact': typeof ContactRoute
  '/curage-canalisation': typeof CurageCanalisationRoute
  '/faq': typeof FaqRoute
  '/hydrocurage': typeof HydrocurageRoute
  '/inspection-camera': typeof InspectionCameraRoute
  '/intervention': typeof InterventionRoute
  '/mentions-legales': typeof MentionsLegalesRoute
  '/politique-confidentialite': typeof PolitiqueConfidentialiteRoute
  '/pompage-assainissement': typeof PompageAssainissementRoute
  '/realisations': typeof RealisationsRoute
  '/sanitaire': typeof SanitaireRoute
  '/services': typeof ServicesRoute
  '/systeme-relevage': typeof SystemeRelevageRoute
  '/tarifs': typeof TarifsRoute
  '/urgence': typeof UrgenceRoute
  '/zones': typeof ZonesRoute
  '/debouchage-canalisation/hauts-de-seine': typeof DebouchageCanalisationHautsDeSeineRoute
  '/debouchage-canalisation/paris': typeof DebouchageCanalisationParisRoute
  '/debouchage-canalisation/seine-saint-denis': typeof DebouchageCanalisationSeineSaintDenisRoute
  '/debouchage-canalisation/': typeof DebouchageCanalisationIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/a-propos': typeof AProposRoute
  '/assurance-decennale': typeof AssuranceDecennaleRoute
  '/bac-a-graisse': typeof BacAGraisseRoute
  '/blog': typeof BlogRoute
  '/canalisations': typeof CanalisationsRoute
  '/contact': typeof ContactRoute
  '/curage-canalisation': typeof CurageCanalisationRoute
  '/faq': typeof FaqRoute
  '/hydrocurage': typeof HydrocurageRoute
  '/inspection-camera': typeof InspectionCameraRoute
  '/intervention': typeof InterventionRoute
  '/mentions-legales': typeof MentionsLegalesRoute
  '/politique-confidentialite': typeof PolitiqueConfidentialiteRoute
  '/pompage-assainissement': typeof PompageAssainissementRoute
  '/realisations': typeof RealisationsRoute
  '/sanitaire': typeof SanitaireRoute
  '/services': typeof ServicesRoute
  '/systeme-relevage': typeof SystemeRelevageRoute
  '/tarifs': typeof TarifsRoute
  '/urgence': typeof UrgenceRoute
  '/zones': typeof ZonesRoute
  '/debouchage-canalisation/hauts-de-seine': typeof DebouchageCanalisationHautsDeSeineRoute
  '/debouchage-canalisation/paris': typeof DebouchageCanalisationParisRoute
  '/debouchage-canalisation/seine-saint-denis': typeof DebouchageCanalisationSeineSaintDenisRoute
  '/debouchage-canalisation': typeof DebouchageCanalisationIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/a-propos': typeof AProposRoute
  '/assurance-decennale': typeof AssuranceDecennaleRoute
  '/bac-a-graisse': typeof BacAGraisseRoute
  '/blog': typeof BlogRoute
  '/canalisations': typeof CanalisationsRoute
  '/contact': typeof ContactRoute
  '/curage-canalisation': typeof CurageCanalisationRoute
  '/faq': typeof FaqRoute
  '/hydrocurage': typeof HydrocurageRoute
  '/inspection-camera': typeof InspectionCameraRoute
  '/intervention': typeof InterventionRoute
  '/mentions-legales': typeof MentionsLegalesRoute
  '/politique-confidentialite': typeof PolitiqueConfidentialiteRoute
  '/pompage-assainissement': typeof PompageAssainissementRoute
  '/realisations': typeof RealisationsRoute
  '/sanitaire': typeof SanitaireRoute
  '/services': typeof ServicesRoute
  '/systeme-relevage': typeof SystemeRelevageRoute
  '/tarifs': typeof TarifsRoute
  '/urgence': typeof UrgenceRoute
  '/zones': typeof ZonesRoute
  '/debouchage-canalisation/hauts-de-seine': typeof DebouchageCanalisationHautsDeSeineRoute
  '/debouchage-canalisation/paris': typeof DebouchageCanalisationParisRoute
  '/debouchage-canalisation/seine-saint-denis': typeof DebouchageCanalisationSeineSaintDenisRoute
  '/debouchage-canalisation/': typeof DebouchageCanalisationIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/a-propos'
    | '/assurance-decennale'
    | '/bac-a-graisse'
    | '/blog'
    | '/canalisations'
    | '/contact'
    | '/curage-canalisation'
    | '/faq'
    | '/hydrocurage'
    | '/inspection-camera'
    | '/intervention'
    | '/mentions-legales'
    | '/politique-confidentialite'
    | '/pompage-assainissement'
    | '/realisations'
    | '/sanitaire'
    | '/services'
    | '/systeme-relevage'
    | '/tarifs'
    | '/urgence'
    | '/zones'
    | '/debouchage-canalisation/hauts-de-seine'
    | '/debouchage-canalisation/paris'
    | '/debouchage-canalisation/seine-saint-denis'
    | '/debouchage-canalisation/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/a-propos'
    | '/assurance-decennale'
    | '/bac-a-graisse'
    | '/blog'
    | '/canalisations'
    | '/contact'
    | '/curage-canalisation'
    | '/faq'
    | '/hydrocurage'
    | '/inspection-camera'
    | '/intervention'
    | '/mentions-legales'
    | '/politique-confidentialite'
    | '/pompage-assainissement'
    | '/realisations'
    | '/sanitaire'
    | '/services'
    | '/systeme-relevage'
    | '/tarifs'
    | '/urgence'
    | '/zones'
    | '/debouchage-canalisation/hauts-de-seine'
    | '/debouchage-canalisation/paris'
    | '/debouchage-canalisation/seine-saint-denis'
    | '/debouchage-canalisation'
  id:
    | '__root__'
    | '/'
    | '/a-propos'
    | '/assurance-decennale'
    | '/bac-a-graisse'
    | '/blog'
    | '/canalisations'
    | '/contact'
    | '/curage-canalisation'
    | '/faq'
    | '/hydrocurage'
    | '/inspection-camera'
    | '/intervention'
    | '/mentions-legales'
    | '/politique-confidentialite'
    | '/pompage-assainissement'
    | '/realisations'
    | '/sanitaire'
    | '/services'
    | '/systeme-relevage'
    | '/tarifs'
    | '/urgence'
    | '/zones'
    | '/debouchage-canalisation/hauts-de-seine'
    | '/debouchage-canalisation/paris'
    | '/debouchage-canalisation/seine-saint-denis'
    | '/debouchage-canalisation/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AProposRoute: typeof AProposRoute
  AssuranceDecennaleRoute: typeof AssuranceDecennaleRoute
  BacAGraisseRoute: typeof BacAGraisseRoute
  BlogRoute: typeof BlogRoute
  CanalisationsRoute: typeof CanalisationsRoute
  ContactRoute: typeof ContactRoute
  CurageCanalisationRoute: typeof CurageCanalisationRoute
  FaqRoute: typeof FaqRoute
  HydrocurageRoute: typeof HydrocurageRoute
  InspectionCameraRoute: typeof InspectionCameraRoute
  InterventionRoute: typeof InterventionRoute
  MentionsLegalesRoute: typeof MentionsLegalesRoute
  PolitiqueConfidentialiteRoute: typeof PolitiqueConfidentialiteRoute
  PompageAssainissementRoute: typeof PompageAssainissementRoute
  RealisationsRoute: typeof RealisationsRoute
  SanitaireRoute: typeof SanitaireRoute
  ServicesRoute: typeof ServicesRoute
  SystemeRelevageRoute: typeof SystemeRelevageRoute
  TarifsRoute: typeof TarifsRoute
  UrgenceRoute: typeof UrgenceRoute
  ZonesRoute: typeof ZonesRoute
  DebouchageCanalisationHautsDeSeineRoute: typeof DebouchageCanalisationHautsDeSeineRoute
  DebouchageCanalisationParisRoute: typeof DebouchageCanalisationParisRoute
  DebouchageCanalisationSeineSaintDenisRoute: typeof DebouchageCanalisationSeineSaintDenisRoute
  DebouchageCanalisationIndexRoute: typeof DebouchageCanalisationIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/a-propos': {
      id: '/a-propos'
      path: '/a-propos'
      fullPath: '/a-propos'
      preLoaderRoute: typeof AProposRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/assurance-decennale': {
      id: '/assurance-decennale'
      path: '/assurance-decennale'
      fullPath: '/assurance-decennale'
      preLoaderRoute: typeof AssuranceDecennaleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bac-a-graisse': {
      id: '/bac-a-graisse'
      path: '/bac-a-graisse'
      fullPath: '/bac-a-graisse'
      preLoaderRoute: typeof BacAGraisseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog': {
      id: '/blog'
      path: '/blog'
      fullPath: '/blog'
      preLoaderRoute: typeof BlogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/canalisations': {
      id: '/canalisations'
      path: '/canalisations'
      fullPath: '/canalisations'
      preLoaderRoute: typeof CanalisationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/curage-canalisation': {
      id: '/curage-canalisation'
      path: '/curage-canalisation'
      fullPath: '/curage-canalisation'
      preLoaderRoute: typeof CurageCanalisationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faq': {
      id: '/faq'
      path: '/faq'
      fullPath: '/faq'
      preLoaderRoute: typeof FaqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hydrocurage': {
      id: '/hydrocurage'
      path: '/hydrocurage'
      fullPath: '/hydrocurage'
      preLoaderRoute: typeof HydrocurageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inspection-camera': {
      id: '/inspection-camera'
      path: '/inspection-camera'
      fullPath: '/inspection-camera'
      preLoaderRoute: typeof InspectionCameraRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/intervention': {
      id: '/intervention'
      path: '/intervention'
      fullPath: '/intervention'
      preLoaderRoute: typeof InterventionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mentions-legales': {
      id: '/mentions-legales'
      path: '/mentions-legales'
      fullPath: '/mentions-legales'
      preLoaderRoute: typeof MentionsLegalesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/politique-confidentialite': {
      id: '/politique-confidentialite'
      path: '/politique-confidentialite'
      fullPath: '/politique-confidentialite'
      preLoaderRoute: typeof PolitiqueConfidentialiteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pompage-assainissement': {
      id: '/pompage-assainissement'
      path: '/pompage-assainissement'
      fullPath: '/pompage-assainissement'
      preLoaderRoute: typeof PompageAssainissementRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/realisations': {
      id: '/realisations'
      path: '/realisations'
      fullPath: '/realisations'
      preLoaderRoute: typeof RealisationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sanitaire': {
      id: '/sanitaire'
      path: '/sanitaire'
      fullPath: '/sanitaire'
      preLoaderRoute: typeof SanitaireRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services': {
      id: '/services'
      path: '/services'
      fullPath: '/services'
      preLoaderRoute: typeof ServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/systeme-relevage': {
      id: '/systeme-relevage'
      path: '/systeme-relevage'
      fullPath: '/systeme-relevage'
      preLoaderRoute: typeof SystemeRelevageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tarifs': {
      id: '/tarifs'
      path: '/tarifs'
      fullPath: '/tarifs'
      preLoaderRoute: typeof TarifsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/urgence': {
      id: '/urgence'
      path: '/urgence'
      fullPath: '/urgence'
      preLoaderRoute: typeof UrgenceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/zones': {
      id: '/zones'
      path: '/zones'
      fullPath: '/zones'
      preLoaderRoute: typeof ZonesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/debouchage-canalisation/': {
      id: '/debouchage-canalisation/'
      path: '/debouchage-canalisation'
      fullPath: '/debouchage-canalisation/'
      preLoaderRoute: typeof DebouchageCanalisationIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/debouchage-canalisation/hauts-de-seine': {
      id: '/debouchage-canalisation/hauts-de-seine'
      path: '/debouchage-canalisation/hauts-de-seine'
      fullPath: '/debouchage-canalisation/hauts-de-seine'
      preLoaderRoute: typeof DebouchageCanalisationHautsDeSeineRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/debouchage-canalisation/paris': {
      id: '/debouchage-canalisation/paris'
      path: '/debouchage-canalisation/paris'
      fullPath: '/debouchage-canalisation/paris'
      preLoaderRoute: typeof DebouchageCanalisationParisRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/debouchage-canalisation/seine-saint-denis': {
      id: '/debouchage-canalisation/seine-saint-denis'
      path: '/debouchage-canalisation/seine-saint-denis'
      fullPath: '/debouchage-canalisation/seine-saint-denis'
      preLoaderRoute: typeof DebouchageCanalisationSeineSaintDenisRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AProposRoute: AProposRoute,
  AssuranceDecennaleRoute: AssuranceDecennaleRoute,
  BacAGraisseRoute: BacAGraisseRoute,
  BlogRoute: BlogRoute,
  CanalisationsRoute: CanalisationsRoute,
  ContactRoute: ContactRoute,
  CurageCanalisationRoute: CurageCanalisationRoute,
  FaqRoute: FaqRoute,
  HydrocurageRoute: HydrocurageRoute,
  InspectionCameraRoute: InspectionCameraRoute,
  InterventionRoute: InterventionRoute,
  MentionsLegalesRoute: MentionsLegalesRoute,
  PolitiqueConfidentialiteRoute: PolitiqueConfidentialiteRoute,
  PompageAssainissementRoute: PompageAssainissementRoute,
  RealisationsRoute: RealisationsRoute,
  SanitaireRoute: SanitaireRoute,
  ServicesRoute: ServicesRoute,
  SystemeRelevageRoute: SystemeRelevageRoute,
  TarifsRoute: TarifsRoute,
  UrgenceRoute: UrgenceRoute,
  ZonesRoute: ZonesRoute,
  DebouchageCanalisationHautsDeSeineRoute:
    DebouchageCanalisationHautsDeSeineRoute,
  DebouchageCanalisationParisRoute: DebouchageCanalisationParisRoute,
  DebouchageCanalisationSeineSaintDenisRoute:
    DebouchageCanalisationSeineSaintDenisRoute,
  DebouchageCanalisationIndexRoute: DebouchageCanalisationIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
